default_env_params = {
    'window_size': 64,
    'model_window_size': 64,
    'enemy_movement': 'aimed',
    'enemy_num': 1,
    'hp': 10,
    'death_penalty': 20,
    'normalize': True,
    'player_speed': 0.03,
    'enemy_speed': 0.02,
    'player_radius': 0.05,
    'enemy_radius': 0.05,
    'action_space': 4, 
    'randomize_player_speed': False,
    'randomize_enemy_speed': False,
    'randomize_player_radius': False,
    'randomize_enemy_radius': False,
    'randomize_enemy_num': False,
}

default_model_hyperparams = {
    'timestep': 5000000,
    'vec_env_num': 64,
    'learning_rate': 0.00005,
    'learning_rate_lambda': False,
    'n_steps': 128,
    'batch_size': 256,
    'n_epochs': 4,
    'gamma': 0.95,
    'gae_lambda': 0.95,
    'clip_range': 0.1,
    'ent_coef': 0.01,
    'vf_coef': 0.5,
    'max_grad_norm': 0.5,
}
